# Glossary {.unnumbered} {#section-glos}

**Assisted reproductive technology**

From records of the hospital delivery admission and can include assisted reproduction, ovulation induction, intracytoplasmic sperm injection (ICSI), embryo transfer, and *in vitro* fertilization (IVF).

**Assisted vaginal delivery**

Vaginal delivery involving the use of forceps and/or vacuum.

**Birth**

Birth refers to the live born or stillborn infant. "Births" are differentiated from "deliveries". For example, a woman who had twins is counted as having one delivery and two births.

**Birth injury**

Any injury to the infant occurring during delivery such as fracture (e.g., femur, clavicle, rib, humerus, depressed skull) or central nervous system trauma (e.g., cerebral hemorrhage, spinal cord hemorrhage, brachial plexus palsy).

**Body mass index (BMI)**

Calculated as weight in kilograms divided by the square of height in metres.

* Underweight: $BMI < 18.5 \, kg/m^{2}$
* Normal weight: $18.5 \, kg/m^{2} \le BMI \le 24.9 \, kg/m^{2}$
* Overweight: $25 \, kg/m^{2} \le BMI \le 29.9 \, kg/m^{2}$
* Obese: $BMI \ge 30 \, kg/m^{2}$

**Breastfeeding status**

Describes the method of infant feeding during the hospital stay. Breastfeeding refers to when the infant was given breast milk: Exclusive denotes that the infant received only breast milk and non-exclusive denotes that the infant received breast milk with supplementation.

**Caesarean section delivery**

Delivery of the fetus through an incision in the abdominal and uterine walls.
Cannabis use Use of cannabis in pregnancy if recorded on the Nova Scotia Prenatal Record.

**Delivery**

A delivery marks the end of pregnancy, regardless of the number of infants born. For example, a woman who had
twins is counted as having one delivery and two births.

**Early neonatal mortality**

Death of a liveborn infant, occurring up to the sixth completed day of life (6 days, 23 hours and 59 minutes).

**Episiotomy**

A mediolateral or midline incision made in the perineum during childbirth.

**Gestational age**

Gestational age is calculated from an algorithm that incorporates information from early ultrasound measurements (before 25 weeks), the first day of the last normal menstrual period (LMP), and a clinical estimate based on a physical examination of the infant shortly after birth. The derivation is primarily based on the date of the mother's last menstrual period (LMP). If LMP is unknown or LMP-estimated gestational age is discordant with that estimated by early fetal ultrasound measurements, then gestational age based on early fetal ultrasound measurements is used. If early fetal ultrasound measurements are unavailable and gestational age based on LMP is discordant from that clinically estimated by the neonatal physical exam, then the clinically estimated gestational age is used.

**Gestational diabetes**

Diabetes mellitus first detected in pregnancy as recorded in the medical record. Please note that the criteria for the diagnosis of gestational diabetes were revised by Diabetes Canada (formerly the Canadian Diabetes Association) in 2013. Therefore, the rates of gestational diabetes were expected to increase as the new criteria are adopted across Nova Scotia, starting approximately in late 2014. [Ref: Canadian Diabetes Association Clinical Practice Guidelines Expert Committee. Canadian Diabetes Association 2013 Clinical Practice Guidelines for the Prevention and Management of Diabetes in Canada. Canadian Journal of Diabetes. 2013;37(suppl1):S1-12].

**Gestational hypertension**

Gestational hypertension is hypertension that is first detected after the 20th week of gestation. Gestational hypertension with significant proteinuria includes those cases denoted as such; severe pre-eclampsia; HELLP syndrome (Hemolysis, Elevated Liver Enzymes, Low Platelets); and eclampsia.

**Gestational weight gain**

Gestational weight gain guidelines set by the US Institute of Medicine and Health Canada are specific to a woman's pre-pregnancy BMI category: Underweight, 12.5 to 18 kg; Normal weight, 11.5 to 16 kg; Overweight, 7 to 11.5 kg; Obese, 5 to 9 kg.

* Inadequate: Below the recommended range.
* Adequate: Within the recommended range.
* Excessive: Above the recommended range.

**Indication for labour induction**

Reason for induction of labour as documented on the medical chart. The 'Other medical reason' category includes maternal diabetes, maternal history of precipitate labour, pruritic uticarial papules and plaques of pregnancy (PUPP), thrombocytopenia, maternal seizure, vaginal bleeding, premature rupture of membranes with clinical
chorioamnionitis, isoimmunization, concern for fetal well being (abnormal biophysical profile, abnormal or atypical non-stress test, abnormal Doppler), oligohydramnios (decreased amniotic fluid), polyhydramnios (increased amniotic fluid), multiple pregnancy, and positive group B Streptococcus with rupture of membranes.

**Infant mortality**

Death of a liveborn infant occurring within the first year of life.

**Interpregnancy weight change**

Calculated as the pre-pregnancy weight in the index pregnancy minus the pre-pregnancy weight in the woman's preceding pregnancy.

**Labour induction**

The initiation of contractions in a pregnant woman who is not in labour to help her achieve a vaginal birth within 24 to 48 hours.

**Laceration**

Maternal perineal laceration, rupture or tear during delivery involving the pelvic floor, perineal muscles, or vaginal muscles ($2^{nd}$ degree), anal sphincter ($3^{rd}$ degree), or rectal mucosa ($4^{th}$ degree).

**Large for gestational age**

See 'Size for gestational age'.

**Live birth**

Live birth refers to birth of an infant with signs of life.

**Macrosomia**

Refers to birth weight beyond two specific thresholds, 4,000 g and 4,500 g. The American College of Obstetricians and Gynecologists supports use of the 4,500 g threshold for diagnosis of macrosomia because morbidity increases sharply beyond this weight, but acknowledges there is some increased risk of morbidity at weights > 4,000 g. [Ref: ACOG Practice Bulletin No.22: Fetal Macrosomia. American College of Obstetricians and Gynecologists, Washington DC 2000]

**Maternal antepartum hospital length of stay**

Hours between maternal admission to the birth facility and delivery.

**Maternal blood transfusion**

One or more maternal transfusions of red blood cells in the antepartum, intrapartum, or postpartum periods.

**Maternal postpartum hospital length of stay**
Hours between delivery and discharge of the mother from the birth facility.

**Medical augmentation**

Use of oxytocin to improve contractions after labour has started spontaneously.

**Neonatal mortality**

Death of a liveborn infant, occurring up to the 27th completed day of life (27 days, 23 hours and 59 minutes).

**Neonatal sepsis**

Isolation of bacterial or fungal or viral organism from blood or cerebrospinal fluid in the symptomatic infant. In addition to blood culture, this includes viral or fungal infection. This definition does not include congenital or postnatal pneumonia.

**Neonatal withdrawal**

Neonatal withdrawal symptoms from maternal dependency on opioid drugs. Does not include neonatal reactions from opioid drugs administered to the mother during labour or delivery.

**Newborn length of stay**

The total number of days a baby stayed in the delivery hospital and transfer hospital(s) (if applicable) before being discharged home. This calculation does not include newborns who have died in-hospital or who have not yet been discharged home.

**Obstetrical intervention**

A delivery that includes any of: induction, medical augmentation, anesthesia, caesarean delivery, vaginal delivery involving the use of forceps and/or vacuum, or episiotomy.

**Opioid agonist maintenance therapy**

Maternal use of methadone, buprenorphine, or other opioid agonist in pregnancy if recorded on the Nova Scotia Prenatal Record.

**Parity**

Number of pregnancies, excluding the present pregnancy, which resulted in the delivery of 1 or more infants weighing 500 g or more at birth (regardless of the outcome of such infants).

**Partner status**

Partnered denotes women who are married or in a common-law relationship.

**Perinatal mortality**

Death of an infant, occurring up to the sixth completed day of life (6 days, 23 hours and 59 minutes). Includes stillbirths and early neonatal deaths.

**Phototherapy**

Exposure of the neonate to coloured light in hospital (birth hospital or readmission in the neonatal period). Phototherapy is given for known or suspected hyperbilirubinemia (jaundice).

**Placenta previa**

Placenta entirely or partially covering the internal os. The diagnosis is not made on ultrasound alone and must be confirmed clinically.

**Placental abruption**

Bleeding from the placental site due to the partial or complete separation of the placenta. The diagnosis is not made on ultrasound alone and must be confirmed clinically.

**Postneonatal mortality**

Death of a liveborn infant weighing 500 g or more at birth, occurring from 28 days to 1 year of life.

**Postpartum hemorrhage**

After the delivery of the fetus, excessive maternal bleeding from the genital tract with an estimated blood loss of greater than 500 mL for vaginal deliveries or 1000 mL for Caesarean section deliveries.

**Pre-eclampsia**

Gestational hypertension with proteinuria, or pre-existing hypertension with superimposed proteinuria. Includes HELLP syndrome (Hemolysis, Elevated Liver Enzymes, Low Platelets).

**Pre-existing diabetes**

Maternal history of either Type 1 or Type 2 diabetes mellitus prior to the current pregnancy.

**Pre-existing hypertension**

Maternal history of hypertensive disease prior to the current pregnancy or prior to 20 weeks' gestation in the current pregnancy.

**Regional anesthesia**

Use of epidural, spinal, and/or pudendal anesthesia during labour and/or delivery.
Respiratory Distress Syndrome (RDS) Grunting, retractions, and decreased air entry - occurring before 3 hours of age and persisting beyond 6 hours of age and not explained by any other disease. Severity of RDS is categorized by the treatment given by the physician as recorded in the medical record:

* Mild: < 35% oxygen
* Moderate: 35% oxygen or continuous positive airway pressure (CPAP)
* Severe: Ventilated
* TTN: Transient tachypnea of the newborn

Note that as medical practice changes with respect to the type of treatment given, the proportion of RDS that is of unknown severity will increase.

**Robson group**

The Robson criteria for the classification of deliveries into ten mutually exclusive groups by maternal characteristics allows comparison of Caesarean section rates at regional and national levels. Please note that for the purposes of this report:

1. group 6 (nulliparous breeches) and group 7 (multiparous breeches) are combined;
2. group 9 (abnormal lies excluding breeches) is omitted due to small numbers. [Ref: Robson MS. Classification of caesarean sections. Fetal and Maternal Medicine Review 2001;12(1):23-39]

**Size for gestational age**

Sex-specific percentiles of birth weight for gestational age relative to a Canadian reference population [Ref: Kramer MS, Platt RW, Wen SW, Joseph KS, Allen A, Abrahamowitz M, Blondel B, Brart G. A New and Improved Population-Based Canadian Reference for Birth Weight for Gestational Age. Pediatrics 2001; 108 (2):e35.](http://pediatrics.aappublications.org/content/108/2/e35.full.html)

**Small for gestational age**

See Size for gestational age.

**Spontaneous vaginal delivery**

Vaginal delivery without the use of forceps or vacuum.

**Stages of labour**

The first stage is the period from the onset of labour until the cervix is fully dilated (10 cm). The second stage is the period from 10 cm dilation of the cervix until the baby is delivered.

**Stillbirth**

The complete expulsion or extraction from its mother after at least 20 weeks pregnancy, or after attaining a weight of 500 g or more, of a fetus in which, after such expulsion or extraction, there is no breathing, beating of the heart, pulsation of the umbilical cord, or unmistakable movement of voluntary muscle.

**Vaginal Birth After Caesarean (VBAC) candidate**

For the purposes of this report, a VBAC candidate is defined as a woman who has had no more than one previous Caesarean section delivery (and that one involved a transverse incision); whose current pregnancy is a singleton in vertex presentation; and who has no contraindications for labour such as previous uterine surgery, cervical disease, HSV or HIV infection, prolapsed cord, or fetal anomaly. On an individual basis when more information is available, such as type of previous Caesarean delivery, other factors are taken into account and women with two previous Caearean deliveries may be considered for VBAC. [Ref: Society of Obstetricians and Gynaecologists of Canada. Guidelines for vaginal birth after previous caesarean birth. SOGC clinical practice guidelines. Number 155, February 2005. Int J Gynaecol Obstet. 2005 Jun;89(3):319-31](https://pubmed.ncbi.nlm.nih.gov/16001462/)
